name: Generate sitemap.xml
on: workflow_call
jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
      - name: Generate sitemap.xml
        uses: cicirello/generate-sitemap@v1.9.1
        with:
          base-url-path: https://florinungur.github.io/flaregun/
          drop-html-extension: true
      - name: Commit sitemap.xml
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git pull
          git commit --all --message "Generate sitemap.xml"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
